---
- name: restart app
  community.docker.docker_compose_v2:
    project_src: /opt/openhabcloud
    state: restarted
    remove_orphans: true

- name: reload nginx
  ansible.builtin.command:
    cmd: docker compose exec nginx nginx -s reload
    chdir: /opt/openhabcloud
  failed_when: false
